### ISSUE TITLE
AFTER UPGRATE MODULE : UndefinedMethodExceptionAttempted to call an undefined method named "parseFile"

### ISSUE THREAD

**Issue by tone87** [PrestaShop/autoupgrade#148]
after automatic upgrate module 1click upgrate show me this error on backoffice only  .. Backoffice not work in all page. HOW I CAN SOLVE THIS ?

FOR DETAIL OF BUG : https://github.com/PrestaShop/PrestaShop/issues/9516

Prestashop version 1.7.4.2

**Displayed log**

(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "parseFile" of class "Symfony\Component\Yaml\Parser".
in YamlFileLoader.php line 667
at YamlFileLoader->loadFile('/var/www/vhosts/fershop.it/httpdocs/app/config/config_dev.yml')in YamlFileLoader.php line 117
at YamlFileLoader->load('/var/www/vhosts/fershop.it/httpdocs/app/config/config_dev.yml', null)in DelegatingLoader.php line 40
at DelegatingLoader->load('/var/www/vhosts/fershop.it/httpdocs/app/config/config_dev.yml')in AppKernel.php line 137
at AppKernel->registerContainerConfiguration(object(DelegatingLoader))in Kernel.php line 774
at Kernel->buildContainer()in Kernel.php line 640
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request), 1, false)in index.php line 88

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Web Server: [e.g. Apache / Nginx / IIS]
 - PHP Version: [e.g. 7.2.9]
 - Module Version [e.g. 4.1.0] -> automatic from 4.0.0

**Comment by tone87** [comment]
i solved with this steps: 
- backup file of this folder /modules/autoupgrade
- after backup delete all file in that folder.
- dowload beta version of this module here https://github.com/PrestaShop/autoupgrade/releases/download/v4.1.0-beta.2/autoupgrade-v4.1.0-beta.2.zip

- extract the contents in modules/autoupgrade folder

- go to phpmyadmin , in modules table, set on column "active" the value 0 at row "autoupgrade"
- reload Backoffice page in your browser
- now  go to phpmyadmin , in modules table, set on column "active" the value 1 at row "autoupgrade"
- reload Backoffice page and it work

**Comment by 99marco9** [comment]
This procedure doesn't solve the problem in my case. I tried it but doesn't work. I try to set on column "active" the value 0 at row "autoupgrade" as the first step, and I receive that exception.

**Comment by 99marco9** [comment]
The solution of Tone87 works with 4.1.0 Beta 2, not with 4.1.0 released. Anyway the problem seems to be on 4.0.0 module, in fact, if I try to deactivate or unistall it, prestashop returns the exception described

**Comment by Quetzacoalt91** [comment]
This issue could be a conflict between `ps_facetedsearch` and `autoupgrade`. Try to temporarily remove it and see if get your BO back.
